export { runPipeline } from './pipeline.js'
export { clampConfidence, dateProximityBonus, amountMatchBonus, agePenalty } from './scoring.js'
export { createMatchingContext, getUnmatchedInvoices, getUnmatchedTransactions } from './context.js'
export { defaultPasses } from './passes/index.js'
export * from './passes/index.js'
