server {

       listen 80;
       listen [::]:80;
       server_name docs.ksefnik.pl;
       return 302 https://$server_name$request_uri;

}

upstream ksefnik-docs
{
    server localhost:7020;
}

server {

       listen 443 ssl;
       listen [::]:443 ssl;
       http2 on;
       ssl_certificate /etc/ssl/ksefnik.cert.pem;
       ssl_certificate_key /etc/ssl/ksefnik.key.pem;
       ssl_client_certificate /etc/ssl/cloudflare.ca.crt;
       ssl_verify_client on;

       gzip on;
       gzip_disable "msie6";
       gzip_vary on;
       gzip_proxied any;
       gzip_comp_level 6;
       gzip_buffers 16 8k;

       server_name docs.ksefnik.pl;

       location / {
              proxy_pass http://ksefnik-docs;
              proxy_set_header Host $host:$server_port;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
       }
}
